name: Android CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type"
        required: true
        default: debug
        type: choice
        options:
          - debug
          - release
jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK
        run: ./gradlew app:assembleDebug
